project:
  type: website
  output-dir: docs
  resources: 
    - "assets/json/*"

execute:
  freeze: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/css/styles.css
    toc: true
    html-math-method: katex
    number-sections: true
    code-fold: false
    page-layout: full
    template-partials: 
      - assets/html/title-block.html

website:
  title: "Julia course"
  navbar:
    tools:
      - icon: github
        href: https://github.com/ocots/course-tse-julia-M1
    background: primary
    left:
      - lecture1.qmd
  back-to-top-navigation: true
  page-footer: 
    center: "Copyright 2024, Olivier Cots" 
