project:
  type: website
  output-dir: docs
  resources: 
    - assets/json/*
  preview:
    port: 4200
    browser: true
    watch-inputs: true

execute:
  freeze: auto

filters:
  - auto-dark
  - code-visibility

format:
  html:
    theme:
      light: [cosmo, assets/css/theme-quarto.scss]      
    css: 
      - assets/css/styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    html-math-method: katex
    number-sections: false
    code-fold: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

website:
  title: "Julia course"
  image: assets/images/logo-julia.png
  favicon: assets/images/logo-julia.svg
  open-graph: true
  twitter-card: true
  site-url: https://ocots.github.io/course-tse-julia/
  repo-url: https://github.com/ocots/course-tse-julia
  issue-url: https://github.com/ocots/course-tse-julia/issues/new/choose
  repo-actions: [edit, source, issue]
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  search: 
    location: navbar
    show-item-context: true
    type: overlay
    keyboard-shortcut: ["?", "H"]
  page-footer: 
    center: "Copyright 2024, Olivier Cots"
  navbar:
    background: light
    logo: assets/images/logo-julia.svg
    logo-alt: "Julia course."
    title: false
    tools:
      - icon: github
        href: https://github.com/ocots/course-tse-julia
    left:
      - text: "Master 1"
        href: M1/index.qmd
      - text: "Master 2"
        href: M2/index.qmd
  sidebar:
    - id: M1
      style: "floating"
      collapse-level: 3
      contents:
        - section: "Master 1"
          href: M1/index.qmd
          contents:
            - text: "Getting started"
              href: M1/getting_started.qmd
            - text: Foretaste of Julia Code
              href: M1/foretaste_of_julia_code.qmd
            - text: Why Julia?
              href: M1/why_julia.qmd
            - text: Syntax
              href: M1/syntax.qmd
            - text: Basic Types
              href: M1/basic-types.qmd
            - text: Advanced Types
              href: M1/advanced-types.qmd
            - text: Multiple Dispatch
              href: M1/fundamentals-multiple_dispatch.qmd
            - text: Modules and Packages
              href: M1/fundamentals-modules_and_packages.qmd
            - text: Metaprogramming
              href: M1/fundamentals-metaprogramming.qmd
            - text: Interoperability
              href: M1/fundamentals-interoperability.qmd
            - text: "---"
    - id: M2
      collapse-level: 3
      contents:
        - section: "Master 2"
          href: M2/index.qmd
          contents:
            - section: "Tutorials"
              contents:
                - text: Distribution of random variables
                  href: M2/exercices-distribution_of_random_variables.qmd
                - text: Linear regression
                  href: M2/exercices-linear_regression.qmd
            - text: "---"